# Throughputs for each type of coating
hrc: 'static_optics/hrc.txt'
8-8732R: 'static_optics/IOI-8-8732R8deg.txt'
8-8261R: 'static_optics/IOI-8-8261R8deg.txt'
8-8431R: 'static_optics/IOI-8-8431R8deg.txt'
8-8380R: 'static_optics/IOI-8-8380R8deg.txt'
6-8648R: 'static_optics/IOI-6-8648R8deg.txt'
6-8763R: 'static_optics/IOI-6-8763R8deg.txt'
1MM48-008: 'static_optics/1MM48-008.txt'
1MM48-009: 'static_optics/1MM48-009.txt'
lens_glass: 'static_optics/lens_transmission.txt'
broadband_ar: 'static_optics/ar_glass.dat'
SBSL7R: 'static_optics/S-BSL7R.txt'
PBM2R: 'static_optics/PBM2R.txt'
qe_excam: 'qe/e2v_excam.txt'
qe_locam: 'qe/e2v_locam.txt'